// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PooledObjectPolicy is an autogenerated mock type for the PooledObjectPolicy type
type PooledObjectPolicy struct {
	mock.Mock
}

// Create provides a mock function with given fields:
func (_m *PooledObjectPolicy) Create() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// Return provides a mock function with given fields: obj
func (_m *PooledObjectPolicy) Return(obj interface{}) bool {
	ret := _m.Called(obj)

	var r0 bool
	if rf, ok := ret.Get(0).(func(interface{}) bool); ok {
		r0 = rf(obj)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
