// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Disposable is an autogenerated mock type for the Disposable type
type Disposable struct {
	mock.Mock
}

// Dispose provides a mock function with given fields:
func (_m *Disposable) Dispose() {
	_m.Called()
}
